DROP TABLE IF EXISTS CD_IFRS9.TB_VETOR_INS_MZ_M_6S;
CREATE EXTERNAL TABLE CD_IFRS9.TB_VETOR_INS_MZ_M_6S(
   COD_ENTIDAD STRING
   ,COD_OFICONT STRING
   ,COD_PRODUCTO STRING
   ,COD_SUBPROD STRING
   ,NUM_CTACONT STRING
   ,NUM_SEQ STRING
   ,AMOUNT  ARRAY<STRING>
   ,AMOUNT_TYPE ARRAY<STRING>
   )
 COMMENT 'TB VETOR MZ PARQUET'
PARTITIONED BY (DT_REFE STRING)
STORED AS PARQUET
LOCATION '/sistemas/ifr/commondata/TB_VETOR_INS_MZ_M'
TBLPROPERTIES ("PARQUET.COMPRESS"="SNAPPY");
