# -*- coding: utf-8 -*-

#!/usr/bin/env python
# Licensed to Cloudera, Inc. under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  Cloudera, Inc. licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from django.conf.urls import patterns, url

urlpatterns = patterns('ifrs9',
                       url(r'^$', 'views.index'),
                       url(r'^alta_ajustes_cliente/$',
                           'views.alta_ajustes_cliente'),
                       url(r'^alta_ajustes_contrato/$',
                           'views.alta_ajustes_contrato'),
                       url(r'^alta_exclusiones_cliente/$',
                           'views.alta_exclusiones_cliente'),
                       url(r'^alta_exclusiones_contrato/$',
                           'views.alta_exclusiones_contrato'),
                       url(r'^buscar_ajustes/$', 'views.buscar_ajustes',
                           name="buscar_ajustes"),
                       url(r'^buscar_exclusiones/$',
                           'views.buscar_exclusiones'),
                       url(r'^buscar_tramos_exclusiones/$',
                           'views.buscar_tramos_exclusiones'),
                       url(r'^buscar_tramos/$', 'views.buscar_tramos'),
                       url(r'^consulta_cliente/$', 'views.consulta_cliente'),
                       url(r'^consulta_contrato/$', 'views.consulta_contrato'),
                       url(r'^detalle_ajuste_cliente/$',
                           'views.detalle_ajuste_cliente'),
                       url(r'^detalle_ajuste_contrato/$',
                           'views.detalle_ajuste_contrato'),
                       url(r'^detalle_ajuste_masivo_cliente/$',
                           'views.detalle_ajuste_masivo_cliente'),
                       url(r'^detalle_ajuste_masivo_contrato/$',
                           'views.detalle_ajuste_masivo_contrato'),
                       url(r'^detalle_ejecucion_cliente/$',
                           'views.detalle_ejecucion_cliente'),
                       url(r'^detalle_ejecucion_contrato/$',
                           'views.detalle_ejecucion_contrato'),
                       url(r'^detalle_exclusion_cliente/$',
                           'views.detalle_exclusion_cliente'),
                       url(r'^detalle_exclusion_contrato/$',
                           'views.detalle_exclusion_contrato'),
                       url(r'^detalle_exclusion_masivo_cliente/$',
                           'views.detalle_exclusion_masivo_cliente'),
                       url(r'^detalle_exclusion_masivo_contrato/$',
                           'views.detalle_exclusion_masivo_contrato'),
                       url(r'^ejecutar_reglas/$', 'views.ejecutar_reglas'),
                       url(r'^importar_reglas/$', 'views.importar_reglas'),
                       url(r'^modal_confirmacion/$',
                           'views.modal_confirmacion'),
                       url(r'^modal_delete/$', 'views.modal_delete'),
                       url(r'^modal_existe/$', 'views.modal_existe'),
                       url(r'^modal_operaciones/$', 'views.modal_operaciones'),
                       url(r'^modal_parametros/$', 'views.modal_parametros'),
                       url(r'^modal_parametros_subida/$',
                           'views.modal_parametros_subida'),
                       url(r'^modal_calculo_provisiones_subida/$',
                           'views.modal_calculo_provisiones_subida'),
                       url(r'^modal_reglas/$', 'views.modal_reglas'),
                       url(r'^modal_setttings/$', 'views.modal_settings'),
                       url(r'^retrieve_ftp_filelist/$',
                           'views.retrieve_ftp_filelist'),
                       url(r'^importar_menu/$', 'views.importar_menu'),
                       url(r'^filter_executions/$', 'views.filter_executions'),
                       url(r'^load_detail_execution/$',
                           'views.load_detail_execution'),
                       url(r'^get_rules_project/$', 'views.get_rules_project'),
                       url(r'^get_params_project/$',
                           'views.get_params_project'),
                       url(r'^get_operations/$', 'views.get_operations'),
                       url(r'^submit_execution/$', 'views.submit_execution'),
                       url(r'^modal_confirmacion_new_execution/$',
                           'views.modal_confirmacion_new_execution'),
                       url(r'^refresh_last_ten_executions/$',
                           'views.refresh_last_ten_executions'),
                       url(r'^comfirm_delete_ajuste/$',
                           'views.comfirm_delete_ajuste'),
                       url(r'^comfirm_delete_exclusion/$',
                           'views.comfirm_delete_exclusion'),
                       url(r'^search_adjustments_application/$',
                           'views.search_adjustments_application'),
                       url(r'^search_exclusions_application/$',
                           'views.search_exclusions_application'),
                       url(r'^search_info_contract_for_adjustment_insert/$',
                           'views.search_info_contract_for_adjustment_insert'),
                       url(r'^search_info_contract_for_adjustment_insert_by_client/$',
                           'views.search_info_contract_for_adjustment_insert_by_client'),
                       url(r'^modal_confirmacion_new_adjustment_contract/$',
                           'views.modal_confirmacion_new_adjustment_contract'),
                       url(r'^modal_confirmacion_new_adjustment_customer/$',
                           'views.modal_confirmacion_new_adjustment_customer'),
                       url(r'^modal_confirmacion_new_exclusion_contract/$',
                           'views.modal_confirmacion_new_exclusion_contract'),
                       url(r'^modal_confirmacion_new_exclusion_customer/$',
                           'views.modal_confirmacion_new_exclusion_customer'),
                       url(r'^add_new_adjustment_by_contract/$',
                           'views.add_new_adjustment_by_contract'),
                       url(r'^add_new_adjustment_by_customer/$',
                           'views.add_new_adjustment_by_customer'),
                       url(r'^add_new_exclusion_by_contract/$',
                           'views.add_new_exclusion_by_contract'),
                       url(r'^add_new_exclusion_by_customer/$',
                           'views.add_new_exclusion_by_customer'),
                       url(r'^application_search_customer/$',
                           'views.application_search_customer'),
                       url(r'^buscar_tramos_contrato/$',
                           'views.buscar_tramos_contrato'),
                       url(r'^application_search_contract/$',
                           'views.application_search_contract'),
                       url(r'^buscar_tramos_exclusion_contrato/$',
                           'views.buscar_tramos_exclusion_contrato'),
                       url(r'^application_search_contract_exclusion/$',
                           'views.application_search_contract_exclusion'),
                       url(r'^modal_conf_promotion/$',
                           'views.modal_conf_promotion'),
                       url(r'^modal_conf_traspaso/$',
                           'views.modal_conf_traspaso'),
                       url(r'^modal_conf_traspaso_exclusion/$',
                           'views.modal_conf_traspaso_exclusion'),
                       url(r'^modal_conf_promotion_exclusion/$',
                           'views.modal_conf_promotion_exclusion'),
                       url(r'^promocionar_ajuste/$',
                           'views.promocionar_ajuste'),
                       url(r'^promocionar_exclusion/$',
                           'views.promocionar_exclusion'),
                       url(r'^traspasar_ajuste/$', 'views.traspasar_ajuste'),
                       url(r'^traspasar_exclusion/$',
                           'views.traspasar_exclusion'),
                       url(r'^detalle_consulta_contrato/$',
                           'views.detalle_consulta_contrato'),
                       url(r'^detalle_consulta_cliente/$',
                           'views.detalle_consulta_cliente'),
                       url(r'^get_detalle_cliente_alta_exclusion_cliente/$',
                           'views.get_detalle_cliente_alta_exclusion_cliente'),
                       url(r'^application_search_customer_exclusion/$',
                           'views.application_search_customer_exclusion'),
                       url(r'^check_user_has_entity/$',
                           'views.check_user_has_entity'),
                       url(r'^getNanModellica/$',
                           'views.getNanModellica'),
                       )
